name: create release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  build:
    needs: tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout Code
      
    - name: Set version env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV  

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: set assembly version
      run: |
       $file = 'src\Signer\Properties\AssemblyInfo.cs'
       $find = '[assembly: AssemblyVersion("0.0.0")]'
       $replace = '[assembly: AssemblyVersion("${{ env.RELEASE_VERSION }}")]'
       (Get-Content $file).replace($find, $replace) | Set-Content $file
       $find = '[assembly: AssemblyFileVersion("0.0.0")]'
       $replace = '[assembly: AssemblyFileVersion("${{ env.RELEASE_VERSION }}")]'
       (Get-Content $file).replace($find, $replace) | Set-Content $file
        
    - name: Restore dependencies
      run: dotnet restore src/Signer/Signer.csproj
    
    - name: Build windows-x64
      run: dotnet publish src/Signer/Signer.csproj -p:PublishProfile=win-x64
    
    - name: Build windows-x86
      run: dotnet publish src/Signer/Signer.csproj -p:PublishProfile=win-x86
    
    - uses: actions/upload-artifact@v3
      with:
        path: src/Signer/bin/publish-win-x64/Signer.exe
        name: Signer-win-x64-${{ env.RELEASE_VERSION }}.exe
    
    - uses: actions/upload-artifact@v3
      with:
        path: src/Signer/bin/publish-win-x86/Signer.exe
        name: Signer-win-x86-${{ env.RELEASE_VERSION }}.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - uses: actions/download-artifact@v3
        with:
          name: Signer-win-x64-${{ env.RELEASE_VERSION }}.exe
          
      - uses: actions/download-artifact@v3
        with:
          name: Signer-win-x86-${{ env.RELEASE_VERSION }}.exe
          
      - name: Release files
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            Signer-win-x64-${{ env.RELEASE_VERSION }}.exe
            Signer-win-x86-${{ env.RELEASE_VERSION }}.exe
